@echo off
REM SmartSign - Railway Deployment Script
REM Deploys template, data, and server to Railway with automated filtering

echo ================================================================================
echo SMARTSIGN TEMPLATE & DATA DEPLOYMENT TO RAILWAY
echo ================================================================================
echo.

REM Check if Railway CLI is installed
where railway >nul 2>&1
if %ERRORLEVEL% NEQ 0 (
    echo [ERROR] Railway CLI not installed
    echo.
    echo Please install Railway CLI:
    echo   npm install -g @railway/cli
    echo.
    echo Or use the web interface: https://railway.app
    pause
    exit /b 1
)

REM Step 1: Run the filter script to generate latest CSV
echo [INFO] Step 1: Generating CSV from Excel...
echo.

python filter_seminarier.py

if %ERRORLEVEL% NEQ 0 (
    echo.
    echo [ERROR] Filter script failed
    pause
    exit /b 1
)

echo.
echo [INFO] Step 2: Verifying required files...
echo.

REM Verify all required files exist
setlocal enabledelayedexpansion
set "files=template_simple.html seminarier.csv server.py iml_background.png iml_logo.png"
set "missing="

for %%F in (%files%) do (
    if not exist "%%F" (
        set "missing=!missing! %%F"
    )
)

if defined missing (
    echo [ERROR] Missing required files:%missing%
    echo.
    echo Required files:
    echo   - template_simple.html (HTML template)
    echo   - seminarier.csv (Generated by filter script)
    echo   - server.py (Railway server)
    echo   - iml_background.png (Background image)
    echo   - iml_logo.png (Logo image)
    echo.
    pause
    exit /b 1
)

echo [OK] template_simple.html found
echo [OK] seminarier.csv found
for %%A in ("seminarier.csv") do (
    echo        Size: %%~zA bytes
    echo        Modified: %%~tA
)
echo [OK] server.py found
echo [OK] iml_background.png found
echo [OK] iml_logo.png found
echo.

REM Step 3: Deploy to Railway
echo [INFO] Step 3: Deploying to Railway...
echo.

railway up

if %ERRORLEVEL% EQU 0 (
    echo.
    echo ================================================================================
    echo [SUCCESS] Deployment complete!
    echo ================================================================================
    echo.
    echo Your SmartSign application is now running on Railway!
    echo.
    echo DEPLOYMENT SUMMARY:
    echo   - HTML Template: template_simple.html
    echo   - CSV Data: seminarier.csv (auto-generated from Excel)
    echo   - Images: iml_background.png, iml_logo.png
    echo   - Server: server.py (Python HTTP server)
    echo.
    echo NEXT STEPS FOR SMARTSIGN:
    echo   1. Run 'railway open' or check https://railway.app dashboard
    echo   2. Get your Railway domain (e.g., your-project.railway.app)
    echo   3. In SmartSign CMS:
    echo      - Go to Publishing > Channels
    echo      - Create new Booking
    echo      - Type: Webpage
    echo      - URL: https://your-project.railway.app/
    echo      - Mode: Live
    echo   4. Save and assign to your digital screen
    echo.
    echo DAILY AUTOMATION:
    echo   This script is run daily by Windows Task Scheduler at 00:00
    echo   It automatically:
    echo      1. Filters seminars from Excel
    echo      2. Generates CSV
    echo      3. Deploys to Railway
    echo   SmartSign will update within 1 hour
    echo.
) else (
    echo.
    echo [ERROR] Deployment failed
    echo.
    echo Troubleshooting:
    echo   1. Run 'railway login' to authenticate
    echo   2. Check your Railway account status
    echo   3. Verify railway.json and Procfile exist
    echo   4. Make sure you have an active Railway project
    echo   5. Verify all required files are present
    echo.
)

echo ================================================================================
pause
